@host = http://localhost
@port = 3000
@url = {{host}}:{{port}}


###get all records from :table

GET {{url}}/users
Content-Type: application/json

###get one records from :table

GET {{url}}/forgalom/247
Content-Type: application/json


###Post new record into :table
POST {{url}}/kategoria
Content-Type: application/json

{
    "categoryName": "Édességek"
    
}


###Login
POST {{url}}/users/login
Content-Type: application/json

{
    "email":"valakik@gmail.com",
    "password": "Secure123"
}
###Registration
POST {{url}}/users/registration
Content-Type: application/json

{
    "email":"valakik@gmail.com",
    "name":"Bigfoot",
    "password": "Secure123",
    "confirm": "Secure123"
}


###Update record :table by :id
PATCH {{url}}/kategoria/14
Content-Type: application/json

{
    "categoryName": "Cukrok"
}


###
GET  {{url}}/users/id/lt/3
Content-Type: application/json

###Delete
DELETE {{url}}/users/10
Content-Type: application/json

